[project]
name = "envoy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "prometheus-fastapi-instrumentator>=7.0.0",
    "ruff>=0.8.2",
]
