apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lavenderses-playground
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: test-nginx
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'

