global:
  scrape_interval: 3s
  scrape_timeout: 2s
  evaluation_interval: 3s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 3s
  scrape_timeout: 2s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: 'fastapi'
  scrape_interval: 3s
  metrics_path: '/metrics'
  static_configs:
    - targets: ['web:8080']

# - job_name: 'envoy'
#   scrape_interval: 3s
#   metrics_path: '/metrics'
#   static_configs:
#     - targets: ['envoy:9901']

