global:
  scrape_interval: 3s
  scrape_timeout: 2s
  evaluation_interval: 3s
alerting:
  alertmanagers:
  - static_configs:
      - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 3s
  scrape_timeout: 2s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
      - localhost:9090

- job_name: pod_exporter2
  kubernetes_sd_configs:
    - role: pod
  relabel_configs:
    - source_labels:
      - __meta_kubernetes_pod_annotation_lavenderses_prometheus_io_scrape
      action: keep
      regex: true
    - source_labels:
        - __meta_kubernetes_pod_ip
        - __meta_kubernetes_pod_annotation_lavenderses_prometheus_io_port
      action: replace
      target_label: __address__
      separator: ":"
      regex: (.+);(.+)
      replacement: $1:$2
    - source_labels:
        - __meta_kubernetes_pod_annotation_lavenderses_prometheus_io_path
      action: replace
      target_label: __metrics_path__
      regex: (.+)

    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: namespace

    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: pod

# - job_name: fastapi
#   scrape_interval: 3s
#   metrics_path: /metrics
#   static_configs:
#     - targets:
#       - fastapi.default.svc.cluster.local:8080

# - job_name: 'envoy'
#   scrape_interval: 3s
#   metrics_path: '/metrics'
#   static_configs:
#     - targets: ['envoy:9901']
