apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: envoy-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: envoy.lavenderses.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: envoy
                port:
                  number: 10001

