/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package playground

import com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy
import com.fasterxml.jackson.databind.annotation.JsonNaming
import kotlinx.coroutines.delay
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.context.annotation.Bean
import org.springframework.web.reactive.function.server.RouterFunction
import org.springframework.web.reactive.function.server.ServerResponse
import org.springframework.web.reactive.function.server.bodyValueAndAwait
import org.springframework.web.reactive.function.server.coRouter

@SpringBootApplication
class App {

    @JsonNaming(SnakeCaseStrategy::class)
    data class Response(
        val sleepMillis: Long,
    )

    @Bean
    fun router(): RouterFunction<ServerResponse> = coRouter {
            GET("/{sleepMillis}") { req ->
                val sleepMillis = checkNotNull(req.pathVariable("sleepMillis")).toLong()
                delay(sleepMillis)
                ok().bodyValueAndAwait(Response(sleepMillis))
            }
        }
}

fun main(args: Array<String>) {
    runApplication<App>(*args)
}
